name: Build Releases

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: =3.9.7
          architecture: x64

      - name: Install CMake
        uses: lukka/get-cmake@v3.21.2

      - name: Download WinLibs MinGW
        uses: carlosperate/download-file-action@v1.0.3
        with:
            file-url: 'https://github.com/brechtsanders/winlibs_mingw/releases/download/11.2.0-13.0.0-9.0.0-ucrt-r2/winlibs-x86_64-posix-seh-gcc-11.2.0-llvm-13.0.0-mingw-w64ucrt-9.0.0-r2.zip'
            file-name: 'mingw.zip'
            location: './'

      - name: Extract MinGW
        run: Expand-Archive ./mingw.zip -DestinationPath ~/


#       - name: Cache multiple paths
#         uses: actions/cache@v2
#         with:
#           path: |
#             ./mingw.zip
#           key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - uses: actions/checkout@v2

      - name: Build googletest
        run: ls ~/mingw64 && ls ~/mingw64 && ./build.ps1 ./winlibs-x86_64-posix-seh-gcc-11.2.0-llvm-13.0.0-mingw-w64ucrt-9.0.0-r2/mingw64/bin/
